

CREATE TABLE `CITIES`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`CITY` CHAR(20) NOT NULL,
	`STATE` CHAR(20) NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `WAREHOUSES`(
	`WID` INT AUTO_INCREMENT PRIMARY KEY,
	`CITY_ID` INT,
	`WNAME` CHAR(30) NOT NULL,
	`LOCATION` CHAR(20) NOT NULL,
	`EXTRA_CONTEXT` JSON NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `STORES`(
	`SID` INT AUTO_INCREMENT PRIMARY KEY,
	`WAREHOUSE_ID` INT,
	`STORE_NAME` CHAR(30) NOT NULL,
	`LOCATION_CITY` CHAR(20) NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `CUSTOMER`(
	`CNO` INT AUTO_INCREMENT PRIMARY KEY,
	`CNAME` CHAR(30) NOT NULL,
	`ADDR` VARCHAR(50) NOT NULL,
	`CU_CITY` CHAR(20) NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `ORDERS`(
	`ONO` INT AUTO_INCREMENT PRIMARY KEY,
	`CUSTOMER_ID` INT,
	`ODATE` DATE NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `ORDERS_ITEM_MAP`(
	`OTM_ID` INT AUTO_INCREMENT PRIMARY KEY,
	`ORDER_ID` INT,
	`ITEM_ID` INT,
	`CUSTOMER_ID` INT,
	`QUANTITY` INT,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `ITEMS`(
	`ITEMNO` INT AUTO_INCREMENT PRIMARY KEY,
	`DESCRIPTION` TEXT NOT NULL,
	`WEIGHT` DECIMAL(5,2) NOT NULL,
	`COST` DECIMAL(5,2) NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE `ITEMS_STORES_MAP`(
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`STORE_ID` INT ,
	`ITEM_ID` INT ,
	`QUANTITY` INT ,
	`DESCRIPTION` TEXT NOT NULL,
	`WEIGHT` DECIMAL(5,2) NOT NULL,
	`COST` DECIMAL(5,2) NOT NULL,
	`IS_ACTIVE` INT(1) DEFAULT 1,
	`IS_DELETED` INT(1) DEFAULT 0,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL,
	`UPDATED_BY` VARCHAR(100) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);

